"""
app.py — FastAPI Application Entry Point
==========================================

This module defines the FastAPI application instance and all HTTP routes
for the Therapeutic AI Chatbot Service.

v0.4.0 Migration Note
---------------------
- Replaced Neo4j with MongoDB Graph RAG.
- Replaced Gemini/OpenAI with AWS Bedrock + Sarvam fallback.
- Removed Neo4j database lifecycle and dependency injection hooks.

Endpoint summary
----------------
POST /chat/send
    Standard JSON request-response endpoint. Calls the full LangGraph
    pipeline (fetch context → retrieve graph context → generate → format
    output) and returns the AI reply with any action cards. A background
    task runs metadata and graph-tuple extraction **after** the response
    is sent so the user is not kept waiting.

POST /chat/stream
    Real-time Server-Sent Events (SSE) streaming endpoint. Yields tokens
    as they are generated by the LLM, then emits action_card and done
    events. Target first-token latency: < 2 seconds.

GET /chat/session/{user_id}/resume
    Sub-500 ms session resumption endpoint. Returns the last 10 messages
    and dropped-session context for instant UI hydration on app open.

GET /health
    Lightweight readiness probe for load balancers and container
    orchestrators.
"""

import logging
from typing import Optional

from fastapi import BackgroundTasks, Depends, FastAPI, HTTPException
from fastapi.responses import StreamingResponse
from motor.motor_asyncio import AsyncIOMotorDatabase

from database import get_db, lifespan
from schemas import ChatMessageRequest, ChatMessageResponse, SessionResumeResponse
from services.extraction import run_background_extraction
from services.graph import run_chat_graph
from services.session_resume import resume_user_session
from services.streaming import stream_chat_graph

# ── Logging ──────────────────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)-8s | %(name)s | %(message)s",
)
logger = logging.getLogger(__name__)

# ── Application ───────────────────────────────────────────────────────────────
app = FastAPI(
    title="Therapeutic AI Chatbot Service",
    description=(
        "Personalized AI therapeutic companion with empathetic, context-aware "
        "conversations, MongoDB Graph RAG memory, inline action cards, E2EE security, "
        "sub-500ms session resumption, real-time SSE streaming, and crisis safeguards."
    ),
    version="0.4.0",
    lifespan=lifespan,
)


# ════════════════════════════════════════════════════════════════════════════
# Routes
# ════════════════════════════════════════════════════════════════════════════


@app.post("/chat/send", response_model=ChatMessageResponse)
async def send_message(
    payload: ChatMessageRequest,
    background_tasks: BackgroundTasks,
    db: AsyncIOMotorDatabase = Depends(get_db),
):
    """
    Process an incoming chat message and return an AI response (JSON).

    Executes the full LangGraph pipeline synchronously and returns the complete reply.
    """
    try:
        logger.info(
            "Incoming JSON message — user=%s session=%s",
            payload.user_id,
            payload.session_id,
        )

        response_data = await run_chat_graph(
            user_id=payload.user_id,
            session_id=payload.session_id,
            user_message=payload.message,
            db=db,
        )

        background_tasks.add_task(
            run_background_extraction,
            user_id=payload.user_id,
            session_id=payload.session_id,
            message=payload.message,
            reply=response_data["reply"],
            db=db,
        )

        return response_data

    except Exception as exc:
        logger.exception(
            "Unhandled error in /chat/send for user=%s session=%s: %s",
            payload.user_id,
            payload.session_id,
            exc,
        )
        raise HTTPException(status_code=500, detail=str(exc))


@app.post("/chat/stream")
async def stream_message(
    payload: ChatMessageRequest,
    background_tasks: BackgroundTasks,
    db: AsyncIOMotorDatabase = Depends(get_db),
):
    """
    Stream the AI response in real-time using Server-Sent Events (SSE).
    """
    try:
        logger.info(
            "Incoming SSE stream request — user=%s session=%s",
            payload.user_id,
            payload.session_id,
        )

        background_tasks.add_task(
            run_background_extraction,
            user_id=payload.user_id,
            session_id=payload.session_id,
            message=payload.message,
            reply="[Streamed Response]",
            db=db,
        )

        return StreamingResponse(
            stream_chat_graph(
                user_id=payload.user_id,
                session_id=payload.session_id,
                user_message=payload.message,
                db=db,
            ),
            media_type="text/event-stream",
            headers={
                "Cache-Control": "no-cache",
                "Connection": "keep-alive",
                "X-Accel-Buffering": "no",
            },
        )

    except Exception as exc:
        logger.exception(
            "Failed to initiate SSE stream for user=%s session=%s: %s",
            payload.user_id,
            payload.session_id,
            exc,
        )
        raise HTTPException(status_code=500, detail=str(exc))


@app.get("/chat/session/{user_id}/resume", response_model=SessionResumeResponse)
async def resume_session(
    user_id: str,
    session_id: Optional[str] = None,
    db: AsyncIOMotorDatabase = Depends(get_db),
):
    """
    Rapid session resumption endpoint (< 500 ms SLA).
    """
    try:
        return await resume_user_session(db, user_id, session_id)
    except Exception as exc:
        logger.exception(
            "Session resumption failed for user=%s session=%s: %s",
            user_id,
            session_id,
            exc,
        )
        raise HTTPException(status_code=500, detail=str(exc))


@app.get("/health")
async def health_check():
    """
    Lightweight readiness / liveness probe.
    """
    return {
        "status": "healthy",
        "service": "therapeutic-ai-chatbot",
        "version": "0.4.0",
    }
