"""
app.py — FastAPI Application Entry Point
==========================================

This module defines the FastAPI application instance and all HTTP routes
for the Therapeutic AI Chatbot Service.

v0.4.0 Migration Note
---------------------
- Replaced Neo4j with MongoDB Graph RAG.
- Replaced Gemini/OpenAI with AWS Bedrock + Sarvam fallback.
- Removed Neo4j database lifecycle and dependency injection hooks.

Endpoint summary
----------------
POST /chat/send
    Standard JSON request-response endpoint. Calls the full LangGraph
    pipeline (fetch context → retrieve graph context → generate → format
    output) and returns the AI reply with any action cards. A background
    task runs metadata and graph-tuple extraction **after** the response
    is sent so the user is not kept waiting.

POST /chat/stream
    Real-time Server-Sent Events (SSE) streaming endpoint. Yields tokens
    as they are generated by the LLM, then emits action_card and done
    events. Target first-token latency: < 2 seconds.

GET /chat/session/{user_id}/resume
    Sub-500 ms session resumption endpoint. Returns the last 10 messages
    and dropped-session context for instant UI hydration on app open.

GET /health
    Lightweight readiness probe for load balancers and container
    orchestrators.
"""

import logging
from typing import Optional

from fastapi import BackgroundTasks, Depends, FastAPI, Header, HTTPException
from fastapi.responses import StreamingResponse
from motor.motor_asyncio import AsyncIOMotorDatabase

from database import get_db, lifespan
from schemas import (
    ChatMessageRequest,
    ChatMessageResponse,
    APMFeedbackRequest,
    LoginRequest,
    LoginResponse,
    MeditationCompleteRequest,
    MeditationFeedbackRequest,
    MeditationPreviewRequest,
    MeditationStartRequest,
    PatternFeedbackRequest,
    AcceptReportTaskRequest,
    ConsultationBatchRequest,
    ConsultationManualRequest,
    ConsultationOverrideRequest,
    SessionReportRequest,
    JournalEntryRequest,
    TaskCompleteRequest,
    TaskCustomPatch,
    TaskCustomRequest,
    SleepLogRequest,
    MoodLogRequest,
    HabitCreateRequest,
    HabitPatchRequest,
    HabitCheckInRequest,
    StreakVisibilityRequest,
    LanguagePreferenceRequest,
    PersonalizationConsentRequest,
    SessionResumeResponse,
    SignupRequest,
    WelcomeRequest,
)
from services.extraction import run_background_extraction
from services.graph import run_chat_graph
from services.session_resume import resume_user_session
from services.streaming import stream_chat_graph
from services.apm import delete_adaptive_memory, record_intervention_feedback
from services.users import (
    authenticate,
    issue_access_token,
    register_user,
    set_personalization_consent,
    set_preferred_language,
    verify_access_token,
)
from prompts import WELCOME_USER_CUE

# ── Logging ──────────────────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)-8s | %(name)s | %(message)s",
)
logger = logging.getLogger(__name__)

# ── Application ───────────────────────────────────────────────────────────────
app = FastAPI(
    title="Therapeutic AI Chatbot Service",
    description=(
        "Personalized AI therapeutic companion with empathetic, context-aware "
        "conversations, MongoDB Graph RAG memory, inline action cards, E2EE security, "
        "sub-500ms session resumption, real-time SSE streaming, and crisis safeguards."
    ),
    version="0.4.0",
    lifespan=lifespan,
)


# ════════════════════════════════════════════════════════════════════════════
# Routes
# ════════════════════════════════════════════════════════════════════════════


async def authenticated_user_id(
    authorization: Optional[str] = Header(default=None),
) -> str:
    if not authorization or not authorization.startswith("Bearer "):
        raise HTTPException(status_code=401, detail="Bearer token required")
    try:
        return verify_access_token(authorization[7:].strip())
    except ValueError as exc:
        raise HTTPException(status_code=401, detail=str(exc)) from exc


def _assert_owner(claimed_user_id: str, authenticated_id: str) -> None:
    if claimed_user_id != authenticated_id:
        raise HTTPException(status_code=403, detail="User identity mismatch")


@app.post("/auth/login", response_model=LoginResponse)
async def login(payload: LoginRequest, db: AsyncIOMotorDatabase = Depends(get_db)):
    """Authenticate by email. Password is never returned."""
    user = await authenticate(db, payload.email, payload.password)
    if not user:
        raise HTTPException(status_code=401, detail="Invalid email or password")
    return LoginResponse(
        user_id=user["user_id"],
        access_token=issue_access_token(user["user_id"]),
        email=user.get("email"),
        name=user.get("name"),
        student_class=user.get("class"),
        school=user.get("school"),
        preferred_language=user.get("preferred_language"),
        age=user.get("age"),
        chief_concern=user.get("chief_concern"),
        board=user.get("board"),
        personalization_consent=user.get("personalization_consent", False),
    )


@app.post("/auth/signup", response_model=LoginResponse, status_code=201)
async def signup(payload: SignupRequest, db: AsyncIOMotorDatabase = Depends(get_db)):
    """Create a new account. Returns the same session payload as login."""
    try:
        user = await register_user(
            db,
            email=payload.email,
            password=payload.password,
            name=payload.name,
        )
    except ValueError as exc:
        detail = str(exc)
        status = 409 if "already exists" in detail.lower() else 400
        raise HTTPException(status_code=status, detail=detail) from exc

    return LoginResponse(
        user_id=user["user_id"],
        access_token=issue_access_token(user["user_id"]),
        email=user.get("email"),
        name=user.get("name"),
        student_class=user.get("class"),
        school=user.get("school"),
        preferred_language=user.get("preferred_language"),
        age=user.get("age"),
        chief_concern=user.get("chief_concern"),
        board=user.get("board"),
        personalization_consent=user.get("personalization_consent", False),
    )


@app.post("/api/language")
async def update_preferred_language(
    payload: LanguagePreferenceRequest,
    user_id: str = Depends(authenticated_user_id),
    db: AsyncIOMotorDatabase = Depends(get_db),
):
    """Store the signed-in user's language. The body user id is not the target."""
    from services.language_preferences import language_write_target

    try:
        language_write_target(user_id, payload.user_id)
        updated = await set_preferred_language(db, user_id, payload.language)
    except PermissionError as exc:
        raise HTTPException(status_code=403, detail=str(exc)) from exc
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc
    if not updated:
        raise HTTPException(status_code=404, detail="Active user not found")
    return {
        "preferred_language": updated.get("preferred_language"),
        "preferred_language_updated_at": updated.get("preferred_language_updated_at"),
    }


@app.post("/api/memory/consent")
async def update_memory_consent(
    payload: PersonalizationConsentRequest,
    user_id: str = Depends(authenticated_user_id),
    db: AsyncIOMotorDatabase = Depends(get_db),
):
    if not await set_personalization_consent(db, user_id, payload.enabled):
        raise HTTPException(status_code=404, detail="Active user not found")
    return {"enabled": payload.enabled}


@app.post("/api/memory/feedback")
async def intervention_feedback(
    payload: APMFeedbackRequest,
    user_id: str = Depends(authenticated_user_id),
    db: AsyncIOMotorDatabase = Depends(get_db),
):
    try:
        recorded = await record_intervention_feedback(
            db,
            user_id,
            edge_id=payload.edge_id,
            intervention_id=payload.intervention_id,
            execution_nonce=payload.execution_nonce,
            event_type=payload.event_type,
            before_state=payload.before_state,
            after_state=payload.after_state,
        )
        return {"recorded": recorded}
    except PermissionError as exc:
        raise HTTPException(status_code=403, detail=str(exc)) from exc
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc


@app.post("/api/patterns/feedback")
async def pattern_feedback(
    payload: PatternFeedbackRequest,
    user_id: str = Depends(authenticated_user_id),
    db: AsyncIOMotorDatabase = Depends(get_db),
):
    """Explicit user confirmation/disagreement on a detected pattern."""
    from services.patterns import record_pattern_feedback

    try:
        return await record_pattern_feedback(
            db,
            user_id=user_id,
            pattern_id=payload.pattern_id,
            event_type=payload.event_type,
            note=payload.note,
        )
    except ValueError as exc:
        raise HTTPException(status_code=404, detail=str(exc)) from exc


@app.delete("/api/memory")
async def delete_memory(
    user_id: str = Depends(authenticated_user_id),
    db: AsyncIOMotorDatabase = Depends(get_db),
):
    """
    Revoke personalized memory material.

    Deletes APM collections and longitudinal user_patterns / pattern_evidence
    for the authenticated user. Chat history and Graph RAG are retained.
    """
    deleted = await delete_adaptive_memory(db, user_id)
    from services.patterns.store import delete_user_patterns
    from student_memory.store import delete_student_memory

    pattern_deleted = await delete_user_patterns(db, user_id)
    facts_deleted = await delete_student_memory(db, user_id)
    meditation_deleted = await db["meditation_executions"].delete_many({"user_id": user_id})
    await db["meditation_offers"].delete_many({"user_id": user_id})
    return {
        "deleted": deleted,
        "patterns_deleted": pattern_deleted,
        "student_facts_deleted": facts_deleted,
        "meditation_executions_deleted": meditation_deleted.deleted_count,
    }


@app.post("/api/memory/consolidate")
async def consolidate_memory(
    user_id: str = Depends(authenticated_user_id),
    db: AsyncIOMotorDatabase = Depends(get_db),
):
    """Rebuild the profile summary from stored facts. Also run by scripts/consolidate_memory.py."""
    from student_memory.store import consolidate_student_memory

    return await consolidate_student_memory(db, user_id)


@app.post("/consultation-evaluation/manual")
async def consultation_manual(
    payload: ConsultationManualRequest,
    user_id: str = Depends(authenticated_user_id),
    db: AsyncIOMotorDatabase = Depends(get_db),
):
    from consultation.evaluate import evaluate_user_for_consultation
    from consultation.roles import target_user

    try:
        target = await target_user(db, user_id, payload.user_id)
    except PermissionError as exc:
        raise HTTPException(status_code=403, detail=str(exc)) from exc
    return await evaluate_user_for_consultation(db, target, trigger="MANUAL", actor=user_id)


@app.post("/consultation-evaluation/manual-override")
async def consultation_manual_override(
    payload: ConsultationOverrideRequest,
    user_id: str = Depends(authenticated_user_id),
    db: AsyncIOMotorDatabase = Depends(get_db),
):
    from consultation.evaluate import manual_override
    from consultation.roles import is_staff

    if not await is_staff(db, user_id):
        raise HTTPException(status_code=403, detail="Staff role required")
    try:
        return await manual_override(
            db, payload.user_id, status=payload.status, reason=payload.reason, actor=user_id
        )
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc


@app.post("/consultation-evaluation/batch")
async def consultation_batch(
    payload: ConsultationBatchRequest,
    user_id: str = Depends(authenticated_user_id),
    db: AsyncIOMotorDatabase = Depends(get_db),
):
    from consultation.evaluate import evaluate_user_for_consultation
    from consultation.roles import is_staff

    if not await is_staff(db, user_id):
        raise HTTPException(status_code=403, detail="Staff role required")
    results = []
    for target in dict.fromkeys(uid.strip() for uid in payload.user_ids if uid and uid.strip()):
        try:
            results.append(
                await evaluate_user_for_consultation(db, target, trigger="BATCH", actor=user_id)
            )
        except Exception as exc:
            logger.exception("Batch evaluation failed for user=%s", target)
            results.append({"user_id": target, "error": str(exc)})
    return {"count": len(results), "results": results}


@app.get("/consultation-evaluation/status")
async def consultation_status(
    user_id: str = Depends(authenticated_user_id),
    db: AsyncIOMotorDatabase = Depends(get_db),
):
    """The signed-in user's latest decision. Signals and audit rows stay internal."""
    from consultation.evaluate import latest_evaluation, unread_notifications

    latest = await latest_evaluation(db, user_id)
    return {
        "status": (latest or {}).get("status") or "NOT_EVALUATED",
        "care_recommendation": (latest or {}).get("care_recommendation"),
        "evaluation_timestamp": (latest or {}).get("evaluation_timestamp"),
        "unread_notifications": await unread_notifications(db, user_id),
    }


@app.post("/chat/welcome", response_model=ChatMessageResponse)
async def welcome_message(
    payload: WelcomeRequest,
    authenticated_id: str = Depends(authenticated_user_id),
    db: AsyncIOMotorDatabase = Depends(get_db),
):
    """
    AI-initiated opening for a new session. Persists only the assistant turn.

    Idempotent: if a welcome (``message_kind=welcome``) already exists for the
    session, return it. If the session already has other messages, do not
    insert a new welcome — return the latest assistant line when available.
    """
    from services.chat_history import (
        get_latest_message,
        get_welcome_message,
        session_has_any_messages,
    )
    from services.security import decrypt_payload

    _assert_owner(payload.user_id, authenticated_id)

    existing_welcome = await get_welcome_message(
        db, payload.user_id, payload.session_id
    )
    if existing_welcome:
        return ChatMessageResponse(
            session_id=payload.session_id,
            reply=decrypt_payload(existing_welcome.get("content", "")),
            action_cards=[],
        )

    if await session_has_any_messages(db, payload.user_id, payload.session_id):
        latest = await get_latest_message(db, payload.user_id, payload.session_id)
        reply = ""
        if latest and latest.get("role") == "assistant":
            reply = decrypt_payload(latest.get("content", ""))
        return ChatMessageResponse(
            session_id=payload.session_id,
            reply=reply,
            action_cards=[],
        )

    try:
        response_data = await run_chat_graph(
            user_id=payload.user_id,
            session_id=payload.session_id,
            user_message=WELCOME_USER_CUE,
            db=db,
            persist_user_message=False,
            opening_turn=True,
        )
        return response_data
    except Exception as exc:
        logger.exception("Welcome turn failed for user=%s: %s", payload.user_id, exc)
        raise HTTPException(status_code=500, detail=str(exc))


@app.post("/chat/send", response_model=ChatMessageResponse)
async def send_message(
    payload: ChatMessageRequest,
    background_tasks: BackgroundTasks,
    authenticated_id: str = Depends(authenticated_user_id),
    db: AsyncIOMotorDatabase = Depends(get_db),
):
    """
    Process an incoming chat message and return an AI response (JSON).

    Executes the full LangGraph pipeline synchronously and returns the complete reply.
    """
    _assert_owner(payload.user_id, authenticated_id)
    try:
        logger.info(
            "Incoming JSON message — user=%s session=%s",
            payload.user_id,
            payload.session_id,
        )

        response_data = await run_chat_graph(
            user_id=payload.user_id,
            session_id=payload.session_id,
            user_message=payload.message,
            db=db,
        )

        background_tasks.add_task(
            run_background_extraction,
            user_id=payload.user_id,
            session_id=payload.session_id,
            message=payload.message,
            reply=response_data["reply"],
            db=db,
        )

        return response_data

    except Exception as exc:
        logger.exception(
            "Unhandled error in /chat/send for user=%s session=%s: %s",
            payload.user_id,
            payload.session_id,
            exc,
        )
        raise HTTPException(status_code=500, detail=str(exc))


@app.post("/chat/stream")
async def stream_message(
    payload: ChatMessageRequest,
    background_tasks: BackgroundTasks,
    authenticated_id: str = Depends(authenticated_user_id),
    db: AsyncIOMotorDatabase = Depends(get_db),
):
    """
    Stream the AI response in real-time using Server-Sent Events (SSE).
    """
    _assert_owner(payload.user_id, authenticated_id)
    try:
        logger.info(
            "Incoming SSE stream request — user=%s session=%s",
            payload.user_id,
            payload.session_id,
        )

        background_tasks.add_task(
            run_background_extraction,
            user_id=payload.user_id,
            session_id=payload.session_id,
            message=payload.message,
            reply="[Streamed Response]",
            db=db,
        )

        return StreamingResponse(
            stream_chat_graph(
                user_id=payload.user_id,
                session_id=payload.session_id,
                user_message=payload.message,
                db=db,
            ),
            media_type="text/event-stream",
            headers={
                "Cache-Control": "no-cache",
                "Connection": "keep-alive",
                "X-Accel-Buffering": "no",
            },
        )

    except Exception as exc:
        logger.exception(
            "Failed to initiate SSE stream for user=%s session=%s: %s",
            payload.user_id,
            payload.session_id,
            exc,
        )
        raise HTTPException(status_code=500, detail=str(exc))


@app.get("/chat/session/{user_id}/resume", response_model=SessionResumeResponse)
async def resume_session(
    user_id: str,
    session_id: Optional[str] = None,
    authenticated_id: str = Depends(authenticated_user_id),
    db: AsyncIOMotorDatabase = Depends(get_db),
):
    """
    Rapid session resumption endpoint (< 500 ms SLA).
    """
    _assert_owner(user_id, authenticated_id)
    try:
        return await resume_user_session(db, user_id, session_id)
    except Exception as exc:
        logger.exception(
            "Session resumption failed for user=%s session=%s: %s",
            user_id,
            session_id,
            exc,
        )
        raise HTTPException(status_code=500, detail=str(exc))


def _public_sleep(doc: dict) -> dict:
    return {
        "user_id": doc.get("user_id"),
        "bedtime": doc.get("bedtime"),
        "wake_up_time": doc.get("wake_up_time"),
        "total_duration_minutes": doc.get("total_duration_minutes"),
        "date": doc.get("date"),
        "created_at": doc.get("created_at"),
    }


def _public_journal(doc: dict, *, preview: bool = False) -> dict:
    from config import get_settings
    from journaling.service import public_entry

    limit = get_settings().JOURNAL_PREVIEW_CHARS if preview else None
    payload = public_entry(doc, preview_chars=limit)
    if doc.get("duplicate"):
        payload["duplicate"] = True
    return payload


@app.post("/journal/entry")
async def post_journal_entry(
    payload: JournalEntryRequest,
    user_id: str = Depends(authenticated_user_id),
    db: AsyncIOMotorDatabase = Depends(get_db),
):
    from journaling.service import create_journal_entry

    try:
        doc = await create_journal_entry(
            db,
            user_id,
            title=payload.title,
            content=payload.content,
            mood=payload.mood,
            tags=payload.tags,
            time_spent=payload.time_spent,
            claimed_user_id=payload.user_id,
        )
    except PermissionError as exc:
        raise HTTPException(status_code=403, detail=str(exc)) from exc
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc
    return _public_journal(doc, preview=False)


@app.get("/journal/recent-entries")
async def journal_recent(
    user_id: str = Depends(authenticated_user_id),
    db: AsyncIOMotorDatabase = Depends(get_db),
):
    from journaling.service import recent_entries

    rows = await recent_entries(db, user_id)
    return {"entries": [_public_journal(row, preview=True) for row in rows]}


@app.get("/journal/entry/{entry_id}")
async def journal_entry(
    entry_id: str,
    user_id: str = Depends(authenticated_user_id),
    db: AsyncIOMotorDatabase = Depends(get_db),
):
    from journaling.service import get_entry

    doc = await get_entry(db, user_id, entry_id)
    if not doc:
        raise HTTPException(status_code=404, detail="Journal entry not found")
    return _public_journal(doc, preview=False)


@app.get("/journal/past-reflections")
async def journal_past(
    user_id: str = Depends(authenticated_user_id),
    db: AsyncIOMotorDatabase = Depends(get_db),
):
    from journaling.service import past_reflections

    rows = await past_reflections(db, user_id)
    return {"entries": [_public_journal(row, preview=True) for row in rows]}


@app.get("/journal/calendar-data")
async def journal_calendar(
    user_id: str = Depends(authenticated_user_id),
    db: AsyncIOMotorDatabase = Depends(get_db),
):
    from journaling.service import calendar_data

    return {"days": await calendar_data(db, user_id)}


@app.get("/journal/favorites")
async def journal_favorites(
    user_id: str = Depends(authenticated_user_id),
    db: AsyncIOMotorDatabase = Depends(get_db),
):
    from journaling.service import favorites

    rows = await favorites(db, user_id)
    return {"entries": [_public_journal(row, preview=True) for row in rows]}


@app.get("/journal/stats")
async def journal_stats(
    user_id: str = Depends(authenticated_user_id),
    db: AsyncIOMotorDatabase = Depends(get_db),
):
    from journaling.service import stats

    return await stats(db, user_id)


@app.get("/journal/monthly-mindfulness")
async def journal_month(
    user_id: str = Depends(authenticated_user_id),
    db: AsyncIOMotorDatabase = Depends(get_db),
):
    from journaling.service import monthly_mindfulness

    return await monthly_mindfulness(db, user_id)


@app.post("/api/sleep")
async def create_sleep(
    payload: SleepLogRequest,
    user_id: str = Depends(authenticated_user_id),
    db: AsyncIOMotorDatabase = Depends(get_db),
):
    """Store one night for the authenticated user. A body user_id cannot retarget it."""
    from sleep.writer import create_sleep_log

    try:
        doc = await create_sleep_log(
            db,
            user_id,
            bedtime=payload.bedtime,
            wake_up_time=payload.wake_up_time,
            date=payload.date,
            total_duration_minutes=payload.total_duration_minutes,
            claimed_user_id=payload.user_id,
        )
    except PermissionError as exc:
        raise HTTPException(status_code=403, detail=str(exc)) from exc
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc
    return _public_sleep(doc)


@app.get("/api/sleep/recent")
async def recent_sleep(
    user_id: str = Depends(authenticated_user_id),
    db: AsyncIOMotorDatabase = Depends(get_db),
):
    from sleep.reader import get_recent_sleep

    doc = await get_recent_sleep(db, user_id)
    return {"sleep": _public_sleep(doc) if doc else None}


@app.get("/api/sleep/history")
async def sleep_history(
    days: int = 7,
    user_id: str = Depends(authenticated_user_id),
    db: AsyncIOMotorDatabase = Depends(get_db),
):
    from sleep.reader import get_sleep_history

    docs = await get_sleep_history(db, user_id, days=days)
    return {"sleep": [_public_sleep(doc) for doc in docs]}


@app.post("/api/mood")
async def log_mood_check_in(
    payload: MoodLogRequest,
    user_id: str = Depends(authenticated_user_id),
    db: AsyncIOMotorDatabase = Depends(get_db),
):
    """One check-in for the authenticated user. A body user_id cannot retarget it.

    Returns `crisis: true` when the note carries crisis wording so the surface
    can offer helplines; the entry is still stored either way.
    """
    from tracking.mood import log_mood

    try:
        return await log_mood(
            db,
            user_id,
            mood=payload.mood,
            score=payload.score,
            note=payload.note,
            input_format=payload.input_format,
            client_event_id=payload.client_event_id,
            logged_at=payload.logged_at,
            claimed_user_id=payload.user_id,
        )
    except (PermissionError, LookupError, ValueError) as exc:
        raise _task_http(exc) from exc


@app.get("/api/mood/recent")
async def recent_mood_check_ins(
    days: Optional[int] = None,
    user_id: str = Depends(authenticated_user_id),
    db: AsyncIOMotorDatabase = Depends(get_db),
):
    from tracking.mood import recent_moods

    return {"moods": await recent_moods(db, user_id, days=days)}


@app.get("/api/habits")
async def list_user_habits(
    include_archived: bool = False,
    user_id: str = Depends(authenticated_user_id),
    db: AsyncIOMotorDatabase = Depends(get_db),
):
    from tracking.habits import list_habits

    try:
        return await list_habits(
            db, user_id, include_archived=include_archived
        )
    except (PermissionError, LookupError, ValueError) as exc:
        raise _task_http(exc) from exc


@app.post("/api/habits")
async def create_user_habit(
    payload: HabitCreateRequest,
    user_id: str = Depends(authenticated_user_id),
    db: AsyncIOMotorDatabase = Depends(get_db),
):
    """Habits are set by the person, not assigned."""
    from tracking.habits import create_habit

    try:
        return await create_habit(
            db,
            user_id,
            title=payload.title,
            frequency=payload.frequency,
            reminder_time=payload.reminder_time,
            claimed_user_id=payload.user_id,
        )
    except (PermissionError, LookupError, ValueError) as exc:
        raise _task_http(exc) from exc


@app.post("/api/habits/streaks")
async def set_habit_streak_visibility(
    payload: StreakVisibilityRequest,
    user_id: str = Depends(authenticated_user_id),
    db: AsyncIOMotorDatabase = Depends(get_db),
):
    """Opting out hides streaks from the chatbot as well as the screen."""
    from tracking.habits import set_streak_visibility

    return await set_streak_visibility(db, user_id, payload.show_streaks)


@app.patch("/api/habits/{habit_id}")
async def patch_user_habit(
    habit_id: str,
    payload: HabitPatchRequest,
    user_id: str = Depends(authenticated_user_id),
    db: AsyncIOMotorDatabase = Depends(get_db),
):
    """Rename, retime, pause, or archive. Completion history is never rewritten."""
    from tracking.habits import update_habit

    try:
        return await update_habit(
            db,
            user_id,
            habit_id,
            title=payload.title,
            frequency=payload.frequency,
            reminder_time=payload.reminder_time,
            status=payload.status,
            claimed_user_id=payload.user_id,
        )
    except (PermissionError, LookupError, ValueError) as exc:
        raise _task_http(exc) from exc


@app.post("/api/habits/{habit_id}/check-in")
async def check_in_user_habit(
    habit_id: str,
    payload: HabitCheckInRequest,
    user_id: str = Depends(authenticated_user_id),
    db: AsyncIOMotorDatabase = Depends(get_db),
):
    """Idempotent: the same day twice returns `already_logged: true`."""
    from tracking.habits import check_in

    try:
        return await check_in(
            db,
            user_id,
            habit_id,
            on_date=payload.on_date,
            claimed_user_id=payload.user_id,
        )
    except (PermissionError, LookupError, ValueError) as exc:
        raise _task_http(exc) from exc


def _task_http(exc: Exception) -> HTTPException:
    if isinstance(exc, PermissionError):
        return HTTPException(status_code=403, detail=str(exc))
    if isinstance(exc, LookupError):
        return HTTPException(status_code=404, detail=str(exc))
    if isinstance(exc, ValueError):
        return HTTPException(status_code=400, detail=str(exc))
    return HTTPException(status_code=500, detail="Task request failed")


@app.get("/api/report_card/tasks/{claimed_user_id}")
async def report_card_tasks(
    claimed_user_id: str,
    user_id: str = Depends(authenticated_user_id),
    db: AsyncIOMotorDatabase = Depends(get_db),
):
    from tasks.store import list_today

    try:
        return await list_today(db, user_id, claimed_user_id=claimed_user_id)
    except PermissionError as exc:
        raise _task_http(exc) from exc


@app.post("/api/report_card/tasks/complete")
async def report_card_complete(
    payload: TaskCompleteRequest,
    user_id: str = Depends(authenticated_user_id),
    db: AsyncIOMotorDatabase = Depends(get_db),
):
    from tasks.store import complete_task

    try:
        return await complete_task(
            db, user_id, payload.task_id, claimed_user_id=payload.user_id
        )
    except (PermissionError, LookupError, ValueError) as exc:
        raise _task_http(exc) from exc


@app.post("/api/report_card/tasks/custom")
async def report_card_custom(
    payload: TaskCustomRequest,
    user_id: str = Depends(authenticated_user_id),
    db: AsyncIOMotorDatabase = Depends(get_db),
):
    from tasks.store import add_custom_task

    try:
        return await add_custom_task(
            db,
            user_id,
            title=payload.title,
            description=payload.description,
            claimed_user_id=payload.user_id,
        )
    except (PermissionError, LookupError, ValueError) as exc:
        raise _task_http(exc) from exc


@app.patch("/api/report_card/tasks/custom/{claimed_user_id}/{task_id}")
async def report_card_patch_custom(
    claimed_user_id: str,
    task_id: str,
    payload: TaskCustomPatch,
    user_id: str = Depends(authenticated_user_id),
    db: AsyncIOMotorDatabase = Depends(get_db),
):
    from tasks.store import patch_custom_task

    try:
        return await patch_custom_task(
            db,
            user_id,
            task_id,
            title=payload.title,
            description=payload.description,
            is_deleted=payload.is_deleted,
            claimed_user_id=claimed_user_id,
        )
    except (PermissionError, LookupError, ValueError) as exc:
        raise _task_http(exc) from exc


@app.post("/api/reports/tasks/accept")
async def accept_report_task(
    payload: AcceptReportTaskRequest,
    user_id: str = Depends(authenticated_user_id),
    db: AsyncIOMotorDatabase = Depends(get_db),
):
    """Add one proposed report task to today's list. The body user id is not the target."""
    from reports.store import accept_proposed_task

    try:
        if payload.user_id and payload.user_id != user_id:
            raise PermissionError("Cannot add another user's task")
        return await accept_proposed_task(
            db,
            user_id,
            payload.session_id,
            payload.task_id,
            claimed_user_id=payload.user_id,
        )
    except (PermissionError, LookupError, ValueError) as exc:
        raise _task_http(exc) from exc


@app.post("/api/session/report")
async def session_report(
    payload: SessionReportRequest,
    user_id: str = Depends(authenticated_user_id),
    db: AsyncIOMotorDatabase = Depends(get_db),
):
    """Post-conversation reading. Ranks at most one meditation from the report state."""
    from services.session_report import generate_session_report

    try:
        return await generate_session_report(
            db, user_id=user_id, session_id=payload.session_id
        )
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc


@app.post("/api/meditation/preview")
async def meditation_preview(
    payload: MeditationPreviewRequest,
    user_id: str = Depends(authenticated_user_id),
    db: AsyncIOMotorDatabase = Depends(get_db),
):
    """Developer preview of the ranked practice. Debug is not sent on chat cards."""
    from services.meditation.service import preview_for_user

    return await preview_for_user(db, user_id, payload.message)


@app.post("/api/meditation/start")
async def meditation_start(
    payload: MeditationStartRequest,
    user_id: str = Depends(authenticated_user_id),
    db: AsyncIOMotorDatabase = Depends(get_db),
):
    from services.meditation.service import start_execution

    try:
        doc = await start_execution(
            db,
            user_id=user_id,
            meditation_id=payload.meditation_id,
            execution_nonce=payload.execution_nonce,
            session_id=payload.session_id or "",
            reason=payload.reason or "",
        )
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc
    return _public_execution(doc)


@app.post("/api/meditation/complete")
async def meditation_complete(
    payload: MeditationCompleteRequest,
    user_id: str = Depends(authenticated_user_id),
    db: AsyncIOMotorDatabase = Depends(get_db),
):
    from services.meditation.service import complete_execution

    try:
        doc = await complete_execution(
            db,
            user_id=user_id,
            execution_id=payload.execution_id,
            execution_nonce=payload.execution_nonce,
            listen_duration_seconds=payload.listen_duration_seconds,
        )
    except ValueError as exc:
        raise HTTPException(status_code=404, detail=str(exc)) from exc
    return _public_execution(doc)


@app.post("/api/meditation/feedback")
async def meditation_feedback(
    payload: MeditationFeedbackRequest,
    user_id: str = Depends(authenticated_user_id),
    db: AsyncIOMotorDatabase = Depends(get_db),
):
    from services.meditation.service import record_feedback

    try:
        doc = await record_feedback(
            db,
            user_id=user_id,
            execution_id=payload.execution_id,
            execution_nonce=payload.execution_nonce,
            feedback=payload.feedback,
        )
    except ValueError as exc:
        message = str(exc)
        status = 400 if "Unsupported" in message else 404
        raise HTTPException(status_code=status, detail=message) from exc
    return _public_execution(doc)


def _public_execution(doc: dict) -> dict:
    return {
        "execution_id": doc.get("execution_id"),
        "meditation_id": doc.get("meditation_id"),
        "status": doc.get("status"),
        "execution_nonce": doc.get("execution_nonce"),
        "user_helpfulness_feedback": doc.get("user_helpfulness_feedback"),
        "listen_duration_seconds": doc.get("listen_duration_seconds") or 0,
    }


@app.get("/health")
async def health_check():
    """
    Lightweight readiness / liveness probe.
    """
    return {
        "status": "healthy",
        "service": "therapeutic-ai-chatbot",
        "version": "0.4.0",
    }
