"""
app.py — FastAPI Application Entry Point
==========================================

This module defines the FastAPI application instance and all HTTP routes
for the Therapeutic AI Chatbot Service.

Endpoint summary
----------------
POST /chat/send
    Standard JSON request-response endpoint.  Calls the full LangGraph
    pipeline (fetch context → retrieve graph context → generate → format
    output) and returns the AI reply with any action cards.  A background
    task runs metadata and graph-tuple extraction **after** the response
    is sent so the user is not kept waiting.

POST /chat/stream
    Real-time Server-Sent Events (SSE) streaming endpoint.  Yields tokens
    as they are generated by the LLM, then emits action_card and done
    events.  Target first-token latency: < 2 seconds.

GET /chat/session/{user_id}/resume
    Sub-500 ms session resumption endpoint.  Returns the last 10 messages
    and dropped-session context for instant UI hydration on app open.

GET /health
    Lightweight readiness probe for load balancers and container
    orchestrators (e.g. Kubernetes liveness/readiness checks).

Architecture note
-----------------
The application is **async-first**; all route handlers are defined with
``async def``.  Database connections are managed via the ``lifespan``
context manager in ``database.py`` and injected per-request via
``Depends(get_db)`` / ``Depends(get_neo4j_driver)``.
"""

import logging
from typing import Optional

from fastapi import BackgroundTasks, Depends, FastAPI, HTTPException
from fastapi.responses import StreamingResponse
from motor.motor_asyncio import AsyncIOMotorDatabase

from database import get_db, get_neo4j_driver, lifespan
from schemas import ChatMessageRequest, ChatMessageResponse, SessionResumeResponse
from services.extraction import run_background_extraction
from services.graph import run_chat_graph
from services.session_resume import resume_user_session
from services.streaming import stream_chat_graph

# ── Logging ──────────────────────────────────────────────────────────────────
# Module-level logger — all route-level logs appear under "app" in log output.
# The root logger is configured once at startup in this module; all other
# modules use ``logging.getLogger(__name__)`` to inherit the configuration.

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)-8s | %(name)s | %(message)s",
)
logger = logging.getLogger(__name__)

# ── Application ───────────────────────────────────────────────────────────────
# The ``lifespan`` parameter replaces the deprecated ``on_startup`` /
# ``on_shutdown`` event hooks and ensures database connections are properly
# closed on graceful shutdown (SIGTERM, Ctrl-C, etc.).

app = FastAPI(
    title="Therapeutic AI Chatbot Service",
    description=(
        "Personalized AI therapeutic companion with empathetic, context-aware "
        "conversations, Graph RAG memory, inline action cards, E2EE security, "
        "sub-500ms session resumption, real-time SSE streaming, and crisis safeguards."
    ),
    version="0.3.0",
    lifespan=lifespan,  # Manages MongoDB and Neo4j connection lifecycle
)


# ════════════════════════════════════════════════════════════════════════════
# Routes
# ════════════════════════════════════════════════════════════════════════════


@app.post("/chat/send", response_model=ChatMessageResponse)
async def send_message(
    payload: ChatMessageRequest,
    background_tasks: BackgroundTasks,
    db: AsyncIOMotorDatabase = Depends(get_db),
    neo4j_driver=Depends(get_neo4j_driver),
):
    """
    Process an incoming chat message and return an AI response (JSON).

    This endpoint executes the full LangGraph pipeline synchronously and
    returns the complete reply before triggering background extraction.

    Flow
    ----
    1. Run the LangGraph chat pipeline:
       fetch_context → retrieve_graph_context → generate → format_output
    2. Return the structured response (reply + action cards) to the client.
    3. Schedule ``run_background_extraction`` as a FastAPI background task
       (runs *after* the response has been sent — zero user-facing latency
       cost).

    Parameters
    ----------
    payload : ChatMessageRequest
        Validated request body containing ``user_id``, ``session_id``,
        and ``message``.
    background_tasks : BackgroundTasks
        FastAPI background task manager (injected automatically).
    db : AsyncIOMotorDatabase
        Motor database instance (injected by ``Depends(get_db)``).
    neo4j_driver : neo4j.AsyncDriver
        Neo4j driver instance (injected by ``Depends(get_neo4j_driver)``).

    Returns
    -------
    ChatMessageResponse
        ``session_id``, ``reply`` text, and ``action_cards`` list.

    Raises
    ------
    HTTPException (500)
        If the LangGraph pipeline raises any unhandled exception.
        The original exception message is included in the detail for
        easier debugging; consider sanitizing this in production.
    """
    try:
        logger.info(
            "Incoming JSON message — user=%s session=%s",
            payload.user_id,
            payload.session_id,
        )

        # Run the full conversational graph (blocking, ~1-3 s depending on LLM)
        response_data = await run_chat_graph(
            user_id=payload.user_id,
            session_id=payload.session_id,
            user_message=payload.message,
            db=db,
            neo4j_driver=neo4j_driver,
        )

        # Schedule non-blocking background extraction for emotions, themes,
        # crisis signals, and Neo4j graph tuples.  The user never waits for this.
        background_tasks.add_task(
            run_background_extraction,
            user_id=payload.user_id,
            session_id=payload.session_id,
            message=payload.message,
            reply=response_data["reply"],
            db=db,
            neo4j_driver=neo4j_driver,
        )

        return response_data

    except Exception as exc:
        # Log the full traceback for server-side debugging.
        logger.exception(
            "Unhandled error in /chat/send for user=%s session=%s: %s",
            payload.user_id,
            payload.session_id,
            exc,
        )
        # Return a 500 to the client with the error message.
        # NOTE: In a production deployment, replace str(exc) with a
        # generic message to avoid leaking internal details to clients.
        raise HTTPException(status_code=500, detail=str(exc))


@app.post("/chat/stream")
async def stream_message(
    payload: ChatMessageRequest,
    background_tasks: BackgroundTasks,
    db: AsyncIOMotorDatabase = Depends(get_db),
    neo4j_driver=Depends(get_neo4j_driver),
):
    """
    Stream the AI response in real-time using Server-Sent Events (SSE).

    Target first-token latency: < 2 seconds.

    The response is an SSE stream where each ``data:`` line is a JSON
    object.  The client should consume the following event types:
    - ``token``        — partial text as generated by the LLM
    - ``action_card``  — a structured card to render in the UI
    - ``crisis_alert`` — emergency helpline resources (if crisis detected)
    - ``error``        — streaming error (the stream will stop after this)
    - ``done``         — signals stream completion

    SSE headers set on the response:
    - ``Cache-Control: no-cache``        — prevent caching of stream events
    - ``Connection: keep-alive``         — maintain the HTTP connection
    - ``X-Accel-Buffering: no``          — disable nginx buffering for SSE

    Parameters
    ----------
    payload : ChatMessageRequest
        Validated request body containing ``user_id``, ``session_id``,
        and ``message``.
    background_tasks : BackgroundTasks
        FastAPI background task manager (injected automatically).
    db : AsyncIOMotorDatabase
        Motor database instance.
    neo4j_driver : neo4j.AsyncDriver
        Neo4j driver instance.

    Returns
    -------
    StreamingResponse
        An async generator wrapped in a ``StreamingResponse`` with
        ``media_type="text/event-stream"``.

    Raises
    ------
    HTTPException (500)
        If the ``StreamingResponse`` cannot be constructed (e.g. the
        streaming generator raises before yielding the first chunk).
        Errors *within* the stream are emitted as SSE ``error`` events
        instead of raising HTTP exceptions.
    """
    try:
        logger.info(
            "Incoming SSE stream request — user=%s session=%s",
            payload.user_id,
            payload.session_id,
        )

        # Schedule background extraction.
        # NOTE: For the streaming path, the full reply is not available at
        # request time (it is built chunk-by-chunk in the generator), so
        # the placeholder "[Streamed Response]" is passed.  A production
        # implementation could collect the full text in the generator and
        # write it back via a queue or shared state.
        background_tasks.add_task(
            run_background_extraction,
            user_id=payload.user_id,
            session_id=payload.session_id,
            message=payload.message,
            reply="[Streamed Response]",  # Placeholder — streaming captures full text internally
            db=db,
            neo4j_driver=neo4j_driver,
        )

        return StreamingResponse(
            stream_chat_graph(
                user_id=payload.user_id,
                session_id=payload.session_id,
                user_message=payload.message,
                db=db,
                neo4j_driver=neo4j_driver,
            ),
            media_type="text/event-stream",
            headers={
                # Prevent proxies and browsers from caching stream events
                "Cache-Control": "no-cache",
                # Instruct the server to keep the HTTP connection alive
                "Connection": "keep-alive",
                # Disable nginx's internal buffering (critical for SSE to work)
                "X-Accel-Buffering": "no",
            },
        )

    except Exception as exc:
        logger.exception(
            "Failed to initiate SSE stream for user=%s session=%s: %s",
            payload.user_id,
            payload.session_id,
            exc,
        )
        raise HTTPException(status_code=500, detail=str(exc))


@app.get("/chat/session/{user_id}/resume", response_model=SessionResumeResponse)
async def resume_session(
    user_id: str,
    session_id: Optional[str] = None,
    db: AsyncIOMotorDatabase = Depends(get_db),
):
    """
    Rapid session resumption endpoint (< 500 ms SLA).

    Called by the front-end immediately on app open (or when the user
    taps "Resume Session" in the sidebar).  Returns the last 10 messages
    and context needed to hydrate the chat UI without any visible loading
    delay.

    If ``session_id`` is not provided, the service auto-detects the most
    recent session for ``user_id`` from the ``messages`` collection.

    Parameters
    ----------
    user_id : str
        Path parameter — the user whose session to resume.
    session_id : str, optional
        Query parameter — the specific session to resume.  If omitted,
        the most recent session is selected automatically.
    db : AsyncIOMotorDatabase
        Motor database instance.

    Returns
    -------
    SessionResumeResponse
        Includes ``recent_messages``, ``dropped_session_context``,
        ``active_emotional_state``, and resolved ``session_id``.

    Raises
    ------
    HTTPException (500)
        If the database query fails unexpectedly.
    """
    try:
        return await resume_user_session(db, user_id, session_id)
    except Exception as exc:
        logger.exception(
            "Session resumption failed for user=%s session=%s: %s",
            user_id,
            session_id,
            exc,
        )
        raise HTTPException(status_code=500, detail=str(exc))


@app.get("/health")
async def health_check():
    """
    Lightweight readiness / liveness probe.

    Used by:
    - Kubernetes liveness and readiness probes
    - Load balancer health checks (e.g. AWS ALB, nginx upstream)
    - CI/CD smoke tests after deployment

    This endpoint does **not** check database connectivity — it only
    confirms that the FastAPI application process is alive and accepting
    requests.  Add a ``/health/deep`` endpoint if you need DB ping checks.

    Returns
    -------
    dict
        JSON object with ``status``, ``service``, and ``version`` keys.
    """
    return {
        "status": "healthy",
        "service": "therapeutic-ai-chatbot",
        "version": "0.3.0",
    }
