"""
services/streaming.py — Server-Sent Events (SSE) Streaming Engine
==================================================================

Implements real-time LLM token streaming for the ``POST /chat/stream``
endpoint.  The target first-token latency is **< 2 seconds**.

v0.4.0 Migration Note
---------------------
- Neo4j graph context replaced with MongoDB graph lookup via ``mongo_graph.py``.
- Dual-LLM streaming fallback follows strict contract:
  Fallback is attempted ONLY if 0 tokens have been emitted. Once token streaming
  has started (>= 1 token yielded), mid-stream failures emit an ``error`` event
  and terminate to avoid stitching partial responses across providers.

SSE Event Types Emitted
-----------------------
Each yielded string follows the SSE wire format::

    event: <event_name>\ndata: <json_payload>\n\n

The following event names are emitted:

``crisis_alert``
    Emitted **immediately** (before any LLM call) when the user's message
    contains known crisis keyword phrases.  Includes helpline data and a
    BOOKING_CARD action card.  The stream then ends with a ``done`` event.

``token``
    A single text chunk as generated by the LLM.  The client appends these
    sequentially to reconstruct the full reply.  Action card delimiter text
    (``<<<ACTION_CARD`` / ``ACTION_CARD>>>``) is filtered out here to keep
    the UI clean.

``action_card``
    Emitted after the full response is assembled (post-processing).
    Contains a complete ``ActionCard`` JSON payload.

``error``
    Emitted if the LLM stream raises an exception mid-generation.  The
    stream stops after this event.

``done``
    Always the final event.  Signals the client that the stream is complete.
"""

import json
from datetime import datetime, timezone
from typing import AsyncGenerator

from langchain_core.messages import AIMessage, HumanMessage, SystemMessage
from motor.motor_asyncio import AsyncIOMotorDatabase

from config.config import get_settings, logger
from llm_provider import get_fallback_llm, get_primary_llm, sanitize_messages_for_bedrock
from prompts import (
    dropped_session_hint,
    format_system_prompt,
    session_phase_instructions,
)
from schemas import ActionCard, CardType
from services.action_boundary import boundary_background, suppress_ordinary_cards
from services.action_cards import (
    attach_apm_execution_metadata,
    ensure_psychiatrist_card,
    parse_action_cards,
)
from services.meditation.cards import ensure_single_meditation_card
from services.patterns.window import evaluate_turn_risk
from services.apm import contains_crisis_signal, get_adaptive_memory_context
from services.chat_history import (
    decrypt_message_doc,
    find_completed_user_turn,
    load_session_messages,
    persist_user_and_assistant,
)
from services.context import fetch_user_context
from services.inner_council import deliberate as inner_council_deliberate
from backend_core.security import CryptoIntegrityError, anonymize_text, decrypt_payload


def _extract_token_text(chunk) -> str:
    """Extract string text from a streaming LLM chunk, handling strings, lists, or message objects."""
    if hasattr(chunk, "content"):
        c = chunk.content
        if isinstance(c, str):
            return c
        elif isinstance(c, list):
            res = []
            for item in c:
                if isinstance(item, str):
                    res.append(item)
                elif isinstance(item, dict) and "text" in item:
                    res.append(item["text"])
                else:
                    res.append(str(item))
            return "".join(res)
        return str(c)
    return str(chunk)

async def stream_welcome_reply(result: dict) -> AsyncGenerator[str, None]:
    """Render a welcome-service result with the existing SSE events.

    One ``token`` event carries the full reply, then any ``action_card``
    events, then ``done``. This does not call the chat model.
    """
    reply = str(result.get("reply") or "")
    if reply:
        yield f"event: token\ndata: {json.dumps({'token': reply})}\n\n"
    for card in result.get("action_cards") or []:
        payload = card if isinstance(card, dict) else {}
        yield f"event: action_card\ndata: {json.dumps(payload)}\n\n"
    yield f"event: done\ndata: {json.dumps({'status': 'completed'})}\n\n"


async def stream_chat_graph(
    user_id: str,
    session_id: str,
    user_message: str,
    db: AsyncIOMotorDatabase,
    neo4j_driver=None,  # Kept for backward-compat signature, ignored
) -> AsyncGenerator[str, None]:
    """
    Async generator that streams the AI response as SSE-formatted strings.

    Called by the FastAPI ``/chat/stream`` route via ``StreamingResponse``.

    Parameters
    ----------
    user_id : str
        The unique user identifier.
    session_id : str
        The unique conversation session identifier.
    user_message : str
        The raw user message text for this turn.
    db : AsyncIOMotorDatabase
        Motor async database handle for message persistence and history.
    neo4j_driver : optional
        Deprecated parameter kept for backward compatibility. Ignored.

    Yields
    ------
    str
        SSE-formatted strings ("event: <name>\ndata: <json>\n\n").
    """
    settings = get_settings()
    now = datetime.now(timezone.utc)

    # Idempotent retry: replay stored assistant reply without regenerating.
    existing = await find_completed_user_turn(db, user_id, session_id, user_message)
    if existing:
        reply = decrypt_payload(existing.get("content", ""))
        for token in reply:
            yield f"event: token\ndata: {json.dumps({'token': token})}\n\n"
        yield f"event: done\ndata: {json.dumps({'status': 'completed'})}\n\n"
        return

    # ── Step 1: Pre-check — Immediate Crisis Intervention (Section 8) ─────────
    if contains_crisis_signal(user_message):
        logger.critical(
            "Crisis keyword detected in stream — user=%s session=%s",
            user_id,
            session_id,
        )

        from services.escalation import open_crisis_fast_track
        from services.language_preferences import crisis_message, resolve_response_language

        await open_crisis_fast_track(db, user_id, session_id=session_id)
        resolved = await resolve_response_language(db, user_id, user_message)
        crisis_reply = crisis_message(resolved["resolved_language"])
        crisis_data = {
            "title": "Immediate Support Available",
            "message": crisis_reply,
            "helplines": [
                {
                    "name": "Tele-MANAS",
                    "number": settings.CRISIS_HELPLINE_TELE_MANAS,
                    "description": "24/7 Toll-free mental health helpline",
                },
                {
                    "name": "Vandrevala Foundation",
                    "number": settings.CRISIS_HELPLINE_VANDREVALA,
                    "description": "24/7 Mental health support",
                },
                {
                    "name": "KIRAN Helpline",
                    "number": settings.CRISIS_HELPLINE_KIRAN,
                    "description": "Govt 24/7 mental health hotline",
                },
                {
                    "name": "AASRA",
                    "number": settings.CRISIS_HELPLINE_AASRA,
                    "description": "24/7 Crisis helpline",
                },
            ],
            "action_card": {
                "card_type": "BOOKING_CARD",
                "title": "Connect to Professional Crisis Support",
                "subtitle": "Speak to a trained counselor immediately",
                "action_payload": {"flow": "crisis_helpline_call"},
            },
        }

        yield f"event: crisis_alert\ndata: {json.dumps(crisis_data)}\n\n"

        try:
            await persist_user_and_assistant(
                db,
                user_id=user_id,
                session_id=session_id,
                user_message=user_message,
                assistant_reply=crisis_data["message"],
                response_language=resolved["resolved_language"],
                response_script=resolved["resolved_script"],
            )
        except Exception:
            logger.exception(
                "Failed to persist crisis exchange for user=%s session=%s",
                user_id,
                session_id,
            )

        yield f"event: done\ndata: {json.dumps({'status': 'completed'})}\n\n"
        return

    # ── Step 2: Fetch MongoDB Context (Memory & Graph) ────────────────────────
    user_context = await fetch_user_context(
        db, user_id, session_id=session_id, user_message=user_message
    )
    user_context["adaptive_memory_context"] = await get_adaptive_memory_context(
        db, user_id, user_message
    )

    graph_context = "No relational graph data available yet."
    try:
        from services.graph_rag import get_user_emotional_graph
        graph_context = await get_user_emotional_graph(db, user_id)
    except Exception as exc:
        logger.warning(
            "Graph RAG fetch error during streaming for user=%s: %s",
            user_id,
            exc,
        )

    # ── Step 3: Load Session History ──────────────────────────────────────────
    history_docs = await load_session_messages(
        db,
        user_id,
        session_id,
        limit=settings.MAX_HISTORY_MESSAGES,
    )
    history_for_hint = [decrypt_message_doc(msg) for msg in history_docs]
    anonymized_user_message = anonymize_text(user_message)
    risk_decision = await evaluate_turn_risk(
        db,
        user_id=user_id,
        session_id=session_id,
        message=user_message,
        opening_turn=False,
    )
    council = inner_council_deliberate(
        user_message,
        history_for_hint,
        opening_turn=False,
        risk_intensity_score=risk_decision.score.risk_intensity_score,
        persistent_distress=risk_decision.persistent_distress,
        attach_psychiatrist_card=False,
        action_card_context=None,
        background_context=boundary_background(
            graph_context,
            user_context.get("adaptive_memory_context") or "",
            user_context.get("pattern_context") or "",
            user_context.get("journal_context") or "",
            user_context.get("sleep_context") or "",
            user_context.get("task_context") or "",
        ),
    )
    stance_block = council.as_prompt_block()
    ordinary_stance = stance_block
    proactive_event_id = ""
    proactive_question = ""
    proactive_topic = ""
    proactive_language = str(user_context.get("preferred_language") or "ENGLISH")
    proactive_script = str(user_context.get("response_script") or "LATIN")
    try:
        from services.proactive.service import (
            evaluate_for_chat_turn,
            stance_with_proactive,
        )

        proactive = await evaluate_for_chat_turn(
            db,
            user_id=user_id,
            session_id=session_id,
            user_message=user_message,
            opening_turn=False,
            message_history=history_for_hint,
            user_context=user_context,
            risk_intensity=risk_decision.score.risk_intensity_score,
            persistent_distress=risk_decision.persistent_distress,
            council=council,
            graph_context=graph_context,
        )
        if proactive.decision == "PROACTIVE_QUESTION" and proactive.question:
            stance_block = stance_with_proactive(stance_block, proactive.question)
            proactive_event_id = proactive.event_id
            proactive_question = proactive.question
            proactive_topic = proactive.topic
            proactive_language = proactive.language or proactive_language
            proactive_script = proactive.script or proactive_script
    except Exception:
        logger.info("Proactive question skipped during stream user=%s", user_id)
    formatted_system = format_system_prompt(
        graph_context=graph_context,
        user_memory=user_context.get("user_memory"),
        recent_moods=user_context.get("recent_moods"),
        active_habits=user_context.get("active_habits"),
        dropped_session_context=dropped_session_hint(history_for_hint),
        user_profile=user_context.get("user_profile"),
        academic_context=user_context.get("academic_context"),
        attendance_context=user_context.get("attendance_context"),
        assessment_context=user_context.get("assessment_context"),
        last_session_context=user_context.get("last_session_context"),
        adaptive_memory_context=user_context.get("adaptive_memory_context"),
        pattern_context=user_context.get("pattern_context"),
        sleep_context=user_context.get("sleep_context"),
        journal_context=user_context.get("journal_context"),
        task_context=user_context.get("task_context"),
        care_context=user_context.get("care_context"),
        student_profile_context=user_context.get("student_profile_context"),
        language_instruction=user_context.get("language_instruction"),
        session_phase=session_phase_instructions(
            opening_turn=False,
            message_history=history_for_hint,
        ),
        response_stance=stance_block,
        action_card_context="",
    )

    raw_messages = [SystemMessage(content=formatted_system)]

    for msg in history_for_hint:
        role = msg.get("role", "user")
        content = msg.get("content", "")
        if role == "user":
            raw_messages.append(HumanMessage(content=content))
        else:
            raw_messages.append(AIMessage(content=content))

    raw_messages.append(HumanMessage(content=anonymized_user_message))

    messages = sanitize_messages_for_bedrock(raw_messages)

    # ── Step 5: Stream from LLM (Pre-first-token fallback contract) ───────────
    # Proactive turns buffer the full reply and validate it before any token
    # is emitted. Ordinary turns keep token-by-token astream unchanged.
    primary_llm = get_primary_llm()
    full_response_chunks = []
    client_token_emitted = False
    buffer_proactive = bool(proactive_event_id)

    async def _ainvoke_complete(llm) -> str:
        from integrations.resilience import resilient_ainvoke

        response = await resilient_ainvoke(llm, messages)
        if isinstance(response, str):
            return response
        return getattr(response, "content", None) or str(response)

    if buffer_proactive:
        try:
            buffered = await _ainvoke_complete(primary_llm)
            full_response_chunks.append(buffered)
        except Exception as exc:
            logger.warning("Primary LLM proactive buffer failed: %s", exc)
            try:
                fallback_llm = get_fallback_llm()
                buffered = await _ainvoke_complete(fallback_llm)
                full_response_chunks.append(buffered)
            except Exception as fallback_exc:
                logger.error("Fallback LLM proactive buffer also failed: %s", fallback_exc)
                payload = {
                    "error": "Unable to start response stream",
                    "retryable": True,
                }
                yield f"event: error\ndata: {json.dumps(payload)}\n\n"
                from services.proactive.delivery import suppress_undelivered

                await suppress_undelivered(
                    db,
                    user_id=user_id,
                    event_id=proactive_event_id,
                    reason="generation_failed",
                )
                return
    else:
        try:
            async for chunk in primary_llm.astream(messages):
                token = _extract_token_text(chunk)
                if not token:
                    continue
                full_response_chunks.append(token)

                if "<<<ACTION_CARD" not in token and "ACTION_CARD>>>" not in token:
                    event_payload = json.dumps({"token": token})
                    yield f"event: token\ndata: {event_payload}\n\n"
                    client_token_emitted = True

        except Exception as exc:
            logger.warning(
                "Primary LLM streaming error (client_token_emitted=%s): %s",
                client_token_emitted,
                exc,
            )

            # Provider switching is legal only before the client has received any
            # token. Discard hidden/empty primary chunks before starting Sarvam.
            if not client_token_emitted:
                full_response_chunks.clear()
                logger.info("Primary failed before first token; switching to Sarvam.")
                try:
                    fallback_llm = get_fallback_llm()
                    async for chunk in fallback_llm.astream(messages):
                        token = _extract_token_text(chunk)
                        if not token:
                            continue
                        full_response_chunks.append(token)

                        if "<<<ACTION_CARD" not in token and "ACTION_CARD>>>" not in token:
                            event_payload = json.dumps({"token": token})
                            yield f"event: token\ndata: {event_payload}\n\n"
                except Exception as fallback_exc:
                    logger.error("Fallback LLM streaming also failed: %s", fallback_exc)
                    payload = {
                        "error": "Unable to start response stream",
                        "retryable": True,
                    }
                    yield f"event: error\ndata: {json.dumps(payload)}\n\n"
                    return
            else:
                # Visible output already left the socket. Store it as incomplete
                # and do not run extraction or treat it as a finished answer.
                payload = {
                    "error": "Response stream interrupted",
                    "retryable": True,
                }
                yield f"event: error\ndata: {json.dumps(payload)}\n\n"
                try:
                    await persist_user_and_assistant(
                        db,
                        user_id=user_id,
                        session_id=session_id,
                        user_message=user_message,
                        assistant_reply="".join(full_response_chunks),
                        incomplete=True,
                    )
                except Exception:
                    logger.exception("Failed to mark incomplete stream user=%s", user_id)
                return

    # ── Step 6: Post-processing — Action Card Parsing ─────────────────────────
    full_text = "".join(full_response_chunks)
    from services.graph import _record_turn_governance
    from services.safety_class import SafetyClass, classify_message

    label = classify_message(user_message)
    governance = await _record_turn_governance(
        db,
        user_id=user_id,
        risk_intensity=risk_decision.score.risk_intensity_score,
        safety_class=label.value,
    )
    care_request = str(governance.get("care_request") or "")
    clean_reply, cards = parse_action_cards(full_text)
    from services.response_validator import FALLBACK_REPLY, validate_reply
    from services.stepping_stone import choose_stepping_stone

    script = str(user_context.get("response_script") or "LATIN")
    pattern_supplied = "USER PATTERN CONTEXT" in str(user_context.get("pattern_context") or "")
    used_generic_fallback = False
    verdict = validate_reply(clean_reply, script=script, pattern_supplied=pattern_supplied)
    if not verdict.ok:
        try:
            from integrations.resilience import resilient_ainvoke

            retry = await resilient_ainvoke(
                get_primary_llm(),
                sanitize_messages_for_bedrock(
                    messages
                    + [
                        HumanMessage(
                            content=(
                                "Rewrite the previous reply. Remove the violation "
                                f"({verdict.reason}). One question at most."
                            )
                        )
                    ]
                ),
            )
            retried = retry.content if hasattr(retry, "content") else str(retry)
            verdict = validate_reply(retried, script=script, pattern_supplied=pattern_supplied)
            clean_reply = retried if verdict.ok else FALLBACK_REPLY
        except Exception:
            clean_reply = FALLBACK_REPLY
            used_generic_fallback = True
            verdict = validate_reply(clean_reply, script=script, pattern_supplied=pattern_supplied)
        if not verdict.ok:
            clean_reply = FALLBACK_REPLY
            used_generic_fallback = True
        cards = []
        if not buffer_proactive:
            yield f"event: correction\ndata: {json.dumps({'reply': clean_reply})}\n\n"
    else:
        label = classify_message(user_message)
        if label is not SafetyClass.NONE:
            cards = []
        else:
            attach_apm_execution_metadata(cards, user_id)
            cards = ensure_psychiatrist_card(
                cards,
                attach=False,
                pattern_id=risk_decision.pattern_id,
                trigger_reason=risk_decision.trigger_reason,
                care_request=care_request,
            )
            offer = await choose_stepping_stone(
                db,
                user_id=user_id,
                message=user_message,
                opening_turn=False,
                safety_class=label,
            )
            cards = ensure_single_meditation_card(
                cards,
                offer.get("offer"),
                suppress=offer.get("kind") != "meditation",
            )
            cards = suppress_ordinary_cards(user_message, cards)

    proactive_final_ok = False
    if buffer_proactive:
        from services.proactive.delivery import (
            ensure_final_proactive_reply,
            suppress_undelivered,
        )

        if used_generic_fallback:
            await suppress_undelivered(
                db,
                user_id,
                proactive_event_id,
                "generation_failed",
            )
        else:
            async def _proactive_rewrite(instruction: str) -> str:
                from integrations.resilience import resilient_ainvoke

                retry = await resilient_ainvoke(
                    get_primary_llm(),
                    sanitize_messages_for_bedrock(
                        messages + [HumanMessage(content=instruction)]
                    ),
                )
                text = retry.content if hasattr(retry, "content") else str(retry)
                return text if isinstance(text, str) else str(text)

            async def _ordinary_fallback(instruction: str) -> str:
                from integrations.resilience import resilient_ainvoke

                ordinary_system = format_system_prompt(
                    graph_context=graph_context,
                    user_memory=user_context.get("user_memory"),
                    recent_moods=user_context.get("recent_moods"),
                    active_habits=user_context.get("active_habits"),
                    dropped_session_context=dropped_session_hint(history_for_hint),
                    user_profile=user_context.get("user_profile"),
                    academic_context=user_context.get("academic_context"),
                    attendance_context=user_context.get("attendance_context"),
                    assessment_context=user_context.get("assessment_context"),
                    last_session_context=user_context.get("last_session_context"),
                    adaptive_memory_context=user_context.get("adaptive_memory_context"),
                    pattern_context=user_context.get("pattern_context"),
                    sleep_context=user_context.get("sleep_context"),
                    journal_context=user_context.get("journal_context"),
                    task_context=user_context.get("task_context"),
                    care_context=user_context.get("care_context"),
                    student_profile_context=user_context.get("student_profile_context"),
                    language_instruction=user_context.get("language_instruction"),
                    session_phase=session_phase_instructions(
                        opening_turn=False,
                        message_history=history_for_hint,
                    ),
                    response_stance=ordinary_stance,
                    action_card_context="",
                )
                ordinary_messages = [SystemMessage(content=ordinary_system)]
                for msg in history_for_hint:
                    role = msg.get("role", "user")
                    content = msg.get("content", "")
                    if role == "user":
                        ordinary_messages.append(HumanMessage(content=content))
                    else:
                        ordinary_messages.append(AIMessage(content=content))
                ordinary_messages.append(HumanMessage(content=anonymized_user_message))
                ordinary_messages.append(HumanMessage(content=instruction))
                retry = await resilient_ainvoke(
                    get_primary_llm(),
                    sanitize_messages_for_bedrock(ordinary_messages),
                )
                text = retry.content if hasattr(retry, "content") else str(retry)
                return text if isinstance(text, str) else str(text)

            final_turn = await ensure_final_proactive_reply(
                clean_reply,
                question=proactive_question,
                topic=proactive_topic,
                script=script,
                language=proactive_language,
                user_id=user_id,
                event_id=proactive_event_id,
                pattern_supplied=pattern_supplied,
                rewrite=_proactive_rewrite,
                ordinary_fallback=_ordinary_fallback,
            )
            clean_reply = final_turn.text
            proactive_final_ok = final_turn.delivered
            if not final_turn.delivered:
                await suppress_undelivered(
                    db,
                    user_id,
                    proactive_event_id,
                    final_turn.reason,
                )
                cards = []
            else:
                clean_reply, cards = parse_action_cards(clean_reply)
                label = classify_message(user_message)
                if label is not SafetyClass.NONE:
                    cards = []

        visible = clean_reply or ""
        if visible:
            yield f"event: token\ndata: {json.dumps({'token': visible})}\n\n"
            client_token_emitted = True

    if cards:
        for card in cards:
            card_payload = json.dumps(card.model_dump())
            yield f"event: action_card\ndata: {card_payload}\n\n"

        try:
            card_docs = [
                {
                    "session_id": session_id,
                    "user_id": user_id,
                    "card": card.model_dump(),
                    "created_at": now,
                }
                for card in cards
            ]
            await db["action_card_logs"].insert_many(card_docs)
        except Exception:
            logger.exception(
                "Failed to log action cards for session=%s",
                session_id,
            )

    # ── Step 7: Persist Messages (idempotent, encrypted, ordered) ─────────────
    try:
        persist_result = await persist_user_and_assistant(
            db,
            user_id=user_id,
            session_id=session_id,
            user_message=user_message,
            assistant_reply=clean_reply,
            response_language=str(user_context.get("preferred_language") or ""),
            response_script=str(user_context.get("response_script") or ""),
        )
        if proactive_event_id and proactive_final_ok:
            assistant_doc = (persist_result or {}).get("assistant_doc") or {}
            message_id = str(assistant_doc.get("message_id") or "")
            if message_id:
                try:
                    from services.proactive.service import mark_delivered

                    await mark_delivered(
                        db,
                        user_id,
                        proactive_event_id,
                        message_id=message_id,
                        session_id=session_id,
                    )
                except Exception:
                    logger.info("Proactive delivered mark skipped stream user=%s", user_id)
        from services.extraction import run_background_extraction

        await run_background_extraction(
            user_id=user_id,
            session_id=session_id,
            message=user_message,
            reply=clean_reply,
            db=db,
        )
    except CryptoIntegrityError:
        raise
    except Exception:
        logger.exception(
            "Failed to persist streamed messages for user=%s session=%s",
            user_id,
            session_id,
        )

    # ── Step 8: Signal Stream Completion ─────────────────────────────────────
    yield f"event: done\ndata: {json.dumps({'status': 'completed'})}\n\n"
