"""
services/streaming.py — Server-Sent Events (SSE) Streaming Engine
==================================================================

Implements real-time LLM token streaming for the ``POST /chat/stream``
endpoint.  The target first-token latency is **< 2 seconds**.

v0.4.0 Migration Note
---------------------
- Neo4j graph context replaced with MongoDB graph lookup via ``mongo_graph.py``.
- Dual-LLM streaming fallback follows strict contract:
  Fallback is attempted ONLY if 0 tokens have been emitted. Once token streaming
  has started (>= 1 token yielded), mid-stream failures emit an ``error`` event
  and terminate to avoid stitching partial responses across providers.

SSE Event Types Emitted
-----------------------
Each yielded string follows the SSE wire format::

    event: <event_name>\ndata: <json_payload>\n\n

The following event names are emitted:

``crisis_alert``
    Emitted **immediately** (before any LLM call) when the user's message
    contains known crisis keyword phrases.  Includes helpline data and a
    BOOKING_CARD action card.  The stream then ends with a ``done`` event.

``token``
    A single text chunk as generated by the LLM.  The client appends these
    sequentially to reconstruct the full reply.  Action card delimiter text
    (``<<<ACTION_CARD`` / ``ACTION_CARD>>>``) is filtered out here to keep
    the UI clean.

``action_card``
    Emitted after the full response is assembled (post-processing).
    Contains a complete ``ActionCard`` JSON payload.

``error``
    Emitted if the LLM stream raises an exception mid-generation.  The
    stream stops after this event.

``done``
    Always the final event.  Signals the client that the stream is complete.
"""

import json
import logging
from datetime import datetime, timezone
from typing import AsyncGenerator

from langchain_core.messages import AIMessage, HumanMessage, SystemMessage
from motor.motor_asyncio import AsyncIOMotorDatabase

from config import get_settings
from llm_provider import get_fallback_llm, get_primary_llm, sanitize_messages_for_bedrock
from prompts import (
    dropped_session_hint,
    format_system_prompt,
    session_phase_instructions,
)
from schemas import ActionCard, CardType
from services.action_cards import (
    attach_apm_execution_metadata,
    ensure_psychiatrist_card,
    parse_action_cards,
)
from services.patterns.window import evaluate_turn_risk, format_action_card_context
from services.apm import contains_crisis_signal, get_adaptive_memory_context
from services.chat_history import (
    decrypt_message_doc,
    find_completed_user_turn,
    load_session_messages,
    persist_user_and_assistant,
)
from services.context import fetch_user_context
from services.inner_council import deliberate as inner_council_deliberate
from services.security import anonymize_text, decrypt_payload

logger = logging.getLogger(__name__)


def _extract_token_text(chunk) -> str:
    """Extract string text from a streaming LLM chunk, handling strings, lists, or message objects."""
    if hasattr(chunk, "content"):
        c = chunk.content
        if isinstance(c, str):
            return c
        elif isinstance(c, list):
            res = []
            for item in c:
                if isinstance(item, str):
                    res.append(item)
                elif isinstance(item, dict) and "text" in item:
                    res.append(item["text"])
                else:
                    res.append(str(item))
            return "".join(res)
        return str(c)
    return str(chunk)

async def stream_chat_graph(
    user_id: str,
    session_id: str,
    user_message: str,
    db: AsyncIOMotorDatabase,
    neo4j_driver=None,  # Kept for backward-compat signature, ignored
) -> AsyncGenerator[str, None]:
    """
    Async generator that streams the AI response as SSE-formatted strings.

    Called by the FastAPI ``/chat/stream`` route via ``StreamingResponse``.

    Parameters
    ----------
    user_id : str
        The unique user identifier.
    session_id : str
        The unique conversation session identifier.
    user_message : str
        The raw user message text for this turn.
    db : AsyncIOMotorDatabase
        Motor async database handle for message persistence and history.
    neo4j_driver : optional
        Deprecated parameter kept for backward compatibility. Ignored.

    Yields
    ------
    str
        SSE-formatted strings ("event: <name>\ndata: <json>\n\n").
    """
    settings = get_settings()
    now = datetime.now(timezone.utc)

    # Idempotent retry: replay stored assistant reply without regenerating.
    existing = await find_completed_user_turn(db, user_id, session_id, user_message)
    if existing:
        reply = decrypt_payload(existing.get("content", ""))
        for token in reply:
            yield f"event: token\ndata: {json.dumps({'token': token})}\n\n"
        yield f"event: done\ndata: {json.dumps({'status': 'completed'})}\n\n"
        return

    # ── Step 1: Pre-check — Immediate Crisis Intervention (Section 8) ─────────
    if contains_crisis_signal(user_message):
        logger.critical(
            "Crisis keyword detected in stream — user=%s session=%s",
            user_id,
            session_id,
        )

        crisis_data = {
            "title": "Immediate Support Available",
            "message": (
                "If you are in distress or having thoughts of self-harm, "
                "please know that you are not alone. Immediate support is available:"
            ),
            "helplines": [
                {
                    "name": "Tele-MANAS",
                    "number": settings.CRISIS_HELPLINE_TELE_MANAS,
                    "description": "24/7 Toll-free mental health helpline",
                },
                {
                    "name": "Vandrevala Foundation",
                    "number": settings.CRISIS_HELPLINE_VANDREVALA,
                    "description": "24/7 Mental health support",
                },
                {
                    "name": "KIRAN Helpline",
                    "number": settings.CRISIS_HELPLINE_KIRAN,
                    "description": "Govt 24/7 mental health hotline",
                },
                {
                    "name": "AASRA",
                    "number": settings.CRISIS_HELPLINE_AASRA,
                    "description": "24/7 Crisis helpline",
                },
            ],
            "action_card": {
                "card_type": "BOOKING_CARD",
                "title": "Connect to Professional Crisis Support",
                "subtitle": "Speak to a trained counselor immediately",
                "action_payload": {"flow": "crisis_helpline_call"},
            },
        }

        yield f"event: crisis_alert\ndata: {json.dumps(crisis_data)}\n\n"

        try:
            await persist_user_and_assistant(
                db,
                user_id=user_id,
                session_id=session_id,
                user_message=user_message,
                assistant_reply=crisis_data["message"],
            )
        except Exception:
            logger.exception(
                "Failed to persist crisis exchange for user=%s session=%s",
                user_id,
                session_id,
            )

        yield f"event: done\ndata: {json.dumps({'status': 'completed'})}\n\n"
        return

    # ── Step 2: Fetch MongoDB Context (Memory & Graph) ────────────────────────
    user_context = await fetch_user_context(
        db, user_id, session_id=session_id, user_message=user_message
    )
    user_context["adaptive_memory_context"] = await get_adaptive_memory_context(
        db, user_id, user_message
    )

    graph_context = "No relational graph data available yet."
    try:
        from services.graph_rag import get_user_emotional_graph
        graph_context = await get_user_emotional_graph(db, user_id)
    except Exception as exc:
        logger.warning(
            "Graph RAG fetch error during streaming for user=%s: %s",
            user_id,
            exc,
        )

    # ── Step 3: Load Session History ──────────────────────────────────────────
    history_docs = await load_session_messages(
        db,
        user_id,
        session_id,
        limit=settings.MAX_HISTORY_MESSAGES,
    )
    history_for_hint = [decrypt_message_doc(msg) for msg in history_docs]
    anonymized_user_message = anonymize_text(user_message)
    risk_decision = await evaluate_turn_risk(
        db,
        user_id=user_id,
        session_id=session_id,
        message=user_message,
        opening_turn=False,
    )
    formatted_system = format_system_prompt(
        graph_context=graph_context,
        user_memory=user_context.get("user_memory"),
        recent_moods=user_context.get("recent_moods"),
        active_habits=user_context.get("active_habits"),
        dropped_session_context=dropped_session_hint(history_for_hint),
        user_profile=user_context.get("user_profile"),
        academic_context=user_context.get("academic_context"),
        attendance_context=user_context.get("attendance_context"),
        assessment_context=user_context.get("assessment_context"),
        last_session_context=user_context.get("last_session_context"),
        adaptive_memory_context=user_context.get("adaptive_memory_context"),
        pattern_context=user_context.get("pattern_context"),
        session_phase=session_phase_instructions(
            opening_turn=False,
            message_history=history_for_hint,
        ),
        response_stance=inner_council_deliberate(
            user_message,
            history_for_hint,
            opening_turn=False,
            risk_intensity_score=risk_decision.score.risk_intensity_score,
            persistent_distress=risk_decision.persistent_distress,
            attach_psychiatrist_card=risk_decision.attach_psychiatrist_card,
            action_card_context=risk_decision.action_card_context,
        ).as_prompt_block(),
        action_card_context=format_action_card_context(
            risk_decision.action_card_context
        ),
    )

    raw_messages = [SystemMessage(content=formatted_system)]

    for msg in history_for_hint:
        role = msg.get("role", "user")
        content = msg.get("content", "")
        if role == "user":
            raw_messages.append(HumanMessage(content=content))
        else:
            raw_messages.append(AIMessage(content=content))

    raw_messages.append(HumanMessage(content=anonymized_user_message))

    messages = sanitize_messages_for_bedrock(raw_messages)

    # ── Step 5: Stream from LLM (Pre-first-token fallback contract) ───────────
    primary_llm = get_primary_llm()
    full_response_chunks = []
    client_token_emitted = False

    try:
        async for chunk in primary_llm.astream(messages):
            token = _extract_token_text(chunk)
            if not token:
                continue
            full_response_chunks.append(token)

            if "<<<ACTION_CARD" not in token and "ACTION_CARD>>>" not in token:
                event_payload = json.dumps({"token": token})
                yield f"event: token\ndata: {event_payload}\n\n"
                client_token_emitted = True

    except Exception as exc:
        logger.warning(
            "Primary LLM streaming error (client_token_emitted=%s): %s",
            client_token_emitted,
            exc,
        )

        # Provider switching is legal only before the client has received any
        # token. Discard hidden/empty primary chunks before starting Sarvam.
        if not client_token_emitted:
            full_response_chunks.clear()
            logger.info("Primary failed before first token; switching to Sarvam.")
            try:
                fallback_llm = get_fallback_llm()
                async for chunk in fallback_llm.astream(messages):
                    token = _extract_token_text(chunk)
                    if not token:
                        continue
                    full_response_chunks.append(token)

                    if "<<<ACTION_CARD" not in token and "ACTION_CARD>>>" not in token:
                        event_payload = json.dumps({"token": token})
                        yield f"event: token\ndata: {event_payload}\n\n"
            except Exception as fallback_exc:
                logger.error("Fallback LLM streaming also failed: %s", fallback_exc)
                payload = {
                    "error": "Unable to start response stream",
                    "retryable": True,
                }
                yield f"event: error\ndata: {json.dumps(payload)}\n\n"
                return
        else:
            # Never stitch providers after visible output. Do not persist the
            # partial assistant response; the client can safely offer retry.
            payload = {
                "error": "Response stream interrupted",
                "retryable": True,
            }
            yield f"event: error\ndata: {json.dumps(payload)}\n\n"
            return

    # ── Step 6: Post-processing — Action Card Parsing ─────────────────────────
    full_text = "".join(full_response_chunks)
    clean_reply, cards = parse_action_cards(full_text)
    attach_apm_execution_metadata(cards, user_id)
    cards = ensure_psychiatrist_card(
        cards,
        attach=risk_decision.attach_psychiatrist_card,
        pattern_id=risk_decision.pattern_id,
        trigger_reason=risk_decision.trigger_reason,
    )

    if cards:
        for card in cards:
            card_payload = json.dumps(card.model_dump())
            yield f"event: action_card\ndata: {card_payload}\n\n"

        try:
            card_docs = [
                {
                    "session_id": session_id,
                    "user_id": user_id,
                    "card": card.model_dump(),
                    "created_at": now,
                }
                for card in cards
            ]
            await db["action_card_logs"].insert_many(card_docs)
        except Exception:
            logger.exception(
                "Failed to log action cards for session=%s",
                session_id,
            )

    # ── Step 7: Persist Messages (idempotent, encrypted, ordered) ─────────────
    try:
        await persist_user_and_assistant(
            db,
            user_id=user_id,
            session_id=session_id,
            user_message=user_message,
            assistant_reply=clean_reply,
        )
    except Exception:
        logger.exception(
            "Failed to persist streamed messages for user=%s session=%s",
            user_id,
            session_id,
        )

    # ── Step 8: Signal Stream Completion ─────────────────────────────────────
    yield f"event: done\ndata: {json.dumps({'status': 'completed'})}\n\n"
