"""
services/streaming.py — Server-Sent Events (SSE) Streaming Engine
==================================================================

Implements real-time LLM token streaming for the ``POST /chat/stream``
endpoint.  The target first-token latency is **< 2 seconds**.

v0.4.0 Migration Note
---------------------
- Neo4j graph context replaced with MongoDB graph lookup via ``mongo_graph.py``.
- Dual-LLM streaming fallback follows strict contract:
  Fallback is attempted ONLY if 0 tokens have been emitted. Once token streaming
  has started (>= 1 token yielded), mid-stream failures emit an ``error`` event
  and terminate to avoid stitching partial responses across providers.

SSE Event Types Emitted
-----------------------
Each yielded string follows the SSE wire format::

    event: <event_name>\ndata: <json_payload>\n\n

The following event names are emitted:

``crisis_alert``
    Emitted **immediately** (before any LLM call) when the user's message
    contains known crisis keyword phrases.  Includes helpline data and a
    BOOKING_CARD action card.  The stream then ends with a ``done`` event.

``token``
    A single text chunk as generated by the LLM.  The client appends these
    sequentially to reconstruct the full reply.  Action card delimiter text
    (``<<<ACTION_CARD`` / ``ACTION_CARD>>>``) is filtered out here to keep
    the UI clean.

``action_card``
    Emitted after the full response is assembled (post-processing).
    Contains a complete ``ActionCard`` JSON payload.

``error``
    Emitted if the LLM stream raises an exception mid-generation.  The
    stream stops after this event.

``done``
    Always the final event.  Signals the client that the stream is complete.
"""

import json
import logging
from datetime import datetime, timezone
from typing import AsyncGenerator

from langchain_core.messages import AIMessage, HumanMessage, SystemMessage
from motor.motor_asyncio import AsyncIOMotorDatabase

from config import get_settings
from llm_provider import get_fallback_llm, get_primary_llm
from prompts import SYSTEM_PROMPT
from schemas import ActionCard, CardType
from services.action_cards import parse_action_cards
from services.context import fetch_user_context
from services.security import anonymize_text, encrypt_payload

logger = logging.getLogger(__name__)

# ── Crisis Keyword Detection ──────────────────────────────────────────────────
_CRISIS_KEYWORDS = [
    "suicide",
    "end my life",
    "want to die",
    "kill myself",
    "self harm",
    "cut myself",
    "overdose",
    "no reason to live",
]


async def stream_chat_graph(
    user_id: str,
    session_id: str,
    user_message: str,
    db: AsyncIOMotorDatabase,
    neo4j_driver=None,  # Kept for backward-compat signature, ignored
) -> AsyncGenerator[str, None]:
    """
    Async generator that streams the AI response as SSE-formatted strings.

    Called by the FastAPI ``/chat/stream`` route via ``StreamingResponse``.

    Parameters
    ----------
    user_id : str
        The unique user identifier.
    session_id : str
        The unique conversation session identifier.
    user_message : str
        The raw user message text for this turn.
    db : AsyncIOMotorDatabase
        Motor async database handle for message persistence and history.
    neo4j_driver : optional
        Deprecated parameter kept for backward compatibility. Ignored.

    Yields
    ------
    str
        SSE-formatted strings ("event: <name>\ndata: <json>\n\n").
    """
    settings = get_settings()
    now = datetime.now(timezone.utc)

    # ── Step 1: Pre-check — Immediate Crisis Intervention (Section 8) ─────────
    msg_lower = user_message.lower()
    if any(kw in msg_lower for kw in _CRISIS_KEYWORDS):
        logger.critical(
            "Crisis keyword detected in stream — user=%s session=%s",
            user_id,
            session_id,
        )

        crisis_data = {
            "title": "Immediate Support Available",
            "message": (
                "If you are in distress or having thoughts of self-harm, "
                "please know that you are not alone. Immediate support is available:"
            ),
            "helplines": [
                {
                    "name": "Tele-MANAS",
                    "number": settings.CRISIS_HELPLINE_TELE_MANAS,
                    "description": "24/7 Toll-free mental health helpline",
                },
                {
                    "name": "Vandrevala Foundation",
                    "number": settings.CRISIS_HELPLINE_VANDREVALA,
                    "description": "24/7 Mental health support",
                },
                {
                    "name": "KIRAN Helpline",
                    "number": settings.CRISIS_HELPLINE_KIRAN,
                    "description": "Govt 24/7 mental health hotline",
                },
                {
                    "name": "AASRA",
                    "number": settings.CRISIS_HELPLINE_AASRA,
                    "description": "24/7 Crisis helpline",
                },
            ],
            "action_card": {
                "card_type": "BOOKING_CARD",
                "title": "Connect to Professional Crisis Support",
                "subtitle": "Speak to a trained counselor immediately",
                "action_payload": {"flow": "crisis_helpline_call"},
            },
        }

        yield f"event: crisis_alert\ndata: {json.dumps(crisis_data)}\n\n"

        enc_user_msg = encrypt_payload(user_message)
        enc_reply = encrypt_payload(crisis_data["message"])

        try:
            await db["messages"].insert_one(
                {
                    "session_id": session_id,
                    "user_id": user_id,
                    "role": "user",
                    "content": enc_user_msg,
                    "created_at": now,
                }
            )
            await db["messages"].insert_one(
                {
                    "session_id": session_id,
                    "user_id": user_id,
                    "role": "assistant",
                    "content": enc_reply,
                    "created_at": now,
                }
            )
        except Exception:
            logger.exception(
                "Failed to persist crisis exchange for user=%s session=%s",
                user_id,
                session_id,
            )

        yield f"event: done\ndata: {json.dumps({'status': 'completed'})}\n\n"
        return

    # ── Step 2: Fetch MongoDB Context (Memory & Graph) ────────────────────────
    user_context = await fetch_user_context(db, user_id)

    graph_context = "No relational graph data available yet."
    try:
        from services.graph_rag import get_user_emotional_graph
        graph_context = await get_user_emotional_graph(db, user_id)
    except Exception as exc:
        logger.warning(
            "Graph RAG fetch error during streaming for user=%s: %s",
            user_id,
            exc,
        )

    # ── Step 3: Load Session History ──────────────────────────────────────────
    cursor = (
        db["messages"]
        .find(
            {"session_id": session_id},
            {"role": 1, "content": 1, "created_at": 1},
        )
        .sort("created_at", -1)
        .limit(settings.MAX_HISTORY_MESSAGES)
    )
    history_docs = await cursor.to_list(length=settings.MAX_HISTORY_MESSAGES)
    history_docs.reverse()

    # ── Step 4: Build Message List ─────────────────────────────────────────────
    anonymized_user_message = anonymize_text(user_message)

    formatted_system = SYSTEM_PROMPT.format(
        graph_context=graph_context,
        user_memory=user_context.get("user_memory", "N/A"),
        recent_moods=user_context.get("recent_moods", "N/A"),
        active_habits=user_context.get("active_habits", "N/A"),
    )

    messages = [SystemMessage(content=formatted_system)]

    for msg in history_docs:
        role = msg.get("role", "user")
        content = msg.get("content", "")
        if role == "user":
            messages.append(HumanMessage(content=content))
        else:
            messages.append(AIMessage(content=content))

    messages.append(HumanMessage(content=anonymized_user_message))

    # ── Step 5: Stream from LLM (Pre-first-token fallback contract) ───────────
    primary_llm = get_primary_llm()
    full_response_chunks = []
    first_token_emitted = False

    try:
        async for chunk in primary_llm.astream(messages):
            first_token_emitted = True
            token = chunk.content if hasattr(chunk, "content") else str(chunk)
            full_response_chunks.append(token)

            if "<<<ACTION_CARD" not in token and "ACTION_CARD>>>" not in token:
                event_payload = json.dumps({"token": token})
                yield f"event: token\ndata: {event_payload}\n\n"

    except Exception as exc:
        logger.warning(
            "Primary LLM streaming error (first_token_emitted=%s): %s",
            first_token_emitted,
            exc,
        )

        # Fallback contract: attempt fallback ONLY if 0 tokens emitted so far
        if not first_token_emitted:
            logger.info("Attempting streaming fallback to fallback LLM...")
            try:
                fallback_llm = get_fallback_llm()
                async for chunk in fallback_llm.astream(messages):
                    token = chunk.content if hasattr(chunk, "content") else str(chunk)
                    full_response_chunks.append(token)

                    if "<<<ACTION_CARD" not in token and "ACTION_CARD>>>" not in token:
                        event_payload = json.dumps({"token": token})
                        yield f"event: token\ndata: {event_payload}\n\n"
            except Exception as fallback_exc:
                logger.error("Fallback LLM streaming also failed: %s", fallback_exc)
                yield f"event: error\ndata: {json.dumps({'error': str(fallback_exc)})}\n\n"
                return
        else:
            # Mid-stream failure: DO NOT stitch responses, emit error and terminate safely
            yield f"event: error\ndata: {json.dumps({'error': str(exc)})}\n\n"
            return

    # ── Step 6: Post-processing — Action Card Parsing ─────────────────────────
    full_text = "".join(full_response_chunks)
    clean_reply, cards = parse_action_cards(full_text)

    if cards:
        for card in cards:
            card_payload = json.dumps(card.model_dump())
            yield f"event: action_card\ndata: {card_payload}\n\n"

        try:
            card_docs = [
                {
                    "session_id": session_id,
                    "user_id": user_id,
                    "card": card.model_dump(),
                    "created_at": now,
                }
                for card in cards
            ]
            await db["action_card_logs"].insert_many(card_docs)
        except Exception:
            logger.exception(
                "Failed to log action cards for session=%s",
                session_id,
            )

    # ── Step 7: Persist Messages (E2EE Encrypted) ─────────────────────────────
    enc_user_msg = encrypt_payload(user_message)
    enc_reply = encrypt_payload(clean_reply)

    try:
        await db["messages"].insert_one(
            {
                "session_id": session_id,
                "user_id": user_id,
                "role": "user",
                "content": enc_user_msg,
                "created_at": now,
            }
        )
        await db["messages"].insert_one(
            {
                "session_id": session_id,
                "user_id": user_id,
                "role": "assistant",
                "content": enc_reply,
                "created_at": now,
            }
        )
    except Exception:
        logger.exception(
            "Failed to persist streamed messages for user=%s session=%s",
            user_id,
            session_id,
        )

    # ── Step 8: Signal Stream Completion ─────────────────────────────────────
    yield f"event: done\ndata: {json.dumps({'status': 'completed'})}\n\n"
