"""Demonstration profiles. Not diagnoses, and not a hardcoded recommendation map."""

from __future__ import annotations

DEMO_PASSWORD = "Zenark@123"

DEMO_PROFILES = [
    {
        "user_id": "med_demo_stress",
        "email": "ananya.rao@zenark.demo",
        "name": "Ananya Rao",
        "preferred_language": "ENGLISH",
        "age": 17,
        "class": "12",
        "school": "Delhi Public School, R.K. Puram",
        "chief_concern": "Short sleep and a heavy exam stretch",
        "sleep_summary": "Frequent short sleep, often four or five hours, especially before tests.",
        "academic_summary": "High academic workload. Several exams are stacked this month.",
        "task_summary": "Pending assignments are piling up.",
        "attendance_summary": "Present most days, but late to the first period after short nights.",
        "journal_summary": "Writes that her mind will not slow down at night.",
        "probe_message": (
            "My chest is tight and I only have a minute. I'm anxious and overwhelmed."
        ),
        "moods": ["anxious", "stressed", "wired"],
        "helpful_meditation_ids": ["311", "311", "311"],
    },
    {
        "user_id": "med_demo_body",
        "email": "rohan.desai@zenark.demo",
        "name": "Rohan Desai",
        "preferred_language": "ENGLISH",
        "age": 16,
        "class": "11",
        "school": "National Public School, Bengaluru",
        "chief_concern": "Wants a longer sit when the day is steady",
        "sleep_summary": "Sleep has been stable, around seven hours.",
        "academic_summary": "Moderate academic pressure. Nothing unusual this week.",
        "task_summary": "Task list is manageable.",
        "attendance_summary": "Attendance is regular.",
        "journal_summary": "Prefers longer mindfulness and has said body scans feel useful.",
        "probe_message": "I feel fairly steady today and I have time to sit with my body.",
        "moods": ["steady", "calm", "okay"],
        "helpful_meditation_ids": ["347", "347", "347"],
    },
    {
        "user_id": "med_demo_kind",
        "email": "leela.nair@zenark.demo",
        "name": "Leela Nair",
        "preferred_language": "ENGLISH",
        "age": 16,
        "class": "11",
        "school": "St. Joseph's, Kochi",
        "chief_concern": "Low mood and pulling back from friends",
        "sleep_summary": "Sleep is uneven but not the main thing she talks about.",
        "academic_summary": "Keeping up, though motivation has dipped.",
        "task_summary": "A few tasks left unfinished.",
        "attendance_summary": "Missed two social clubs, classes otherwise attended.",
        "journal_summary": "Low mood. Has been withdrawing and is hard on herself.",
        "probe_message": "I've been feeling low and I've been pulling away from people.",
        "moods": ["low", "flat", "lonely"],
        "helpful_meditation_ids": ["356", "356"],
    },
    {
        "user_id": "med_demo_focus",
        "email": "ishaan.mehta@zenark.demo",
        "name": "Ishaan Mehta",
        "preferred_language": "ENGLISH",
        "age": 17,
        "class": "12",
        "school": "Ryan International, Mumbai",
        "chief_concern": "Attention slips when the task list is long",
        "sleep_summary": "Sleep is adequate.",
        "academic_summary": "High academic workload across physics and maths.",
        "task_summary": "Large task backlog. Difficulty getting started and staying with one task.",
        "attendance_summary": "Attendance is fine. Focus in class is the harder part.",
        "journal_summary": "Says focus and productivity practices have actually helped.",
        "probe_message": "I can't focus. The backlog is huge and my attention is scattered.",
        "moods": ["scattered", "restless", "busy"],
        "helpful_meditation_ids": ["331", "331", "331"],
    },
    {
        "user_id": "med_demo_sleep",
        "email": "sara.qureshi@zenark.demo",
        "name": "Sara Qureshi",
        "preferred_language": "ENGLISH",
        "age": 15,
        "class": "10",
        "school": "La Martiniere, Lucknow",
        "chief_concern": "Evening stress that makes it hard to fall asleep",
        "sleep_summary": "Evening stress. Preparing for sleep is the hard part, not the morning.",
        "academic_summary": "School load is ordinary.",
        "task_summary": "Homework is usually done before dinner.",
        "attendance_summary": "Attendance is steady.",
        "journal_summary": "Body scan and sleep practices have felt helpful at night.",
        "probe_message": "It's night and I need to wind down. I can't sleep yet.",
        "moods": ["tired", "restless", "evening stress"],
        "helpful_meditation_ids": ["324", "324"],
    },
]
